//
// Generated by sedonac 1.2.28
<<<<<<< HEAD
// 06-May-2016 22:45
=======
// 06-May-2016 22:50
>>>>>>> analogout
//

#ifndef SEDONAC_SEDONA_PLATFORM_H
#define SEDONAC_SEDONA_PLATFORM_H

#define PLATFORM_ID "tridium-generic-unix-1.2.28"

#endif
