//
// Generated by sedonac 1.2.28
<<<<<<< HEAD
// 07-May-2016 13:40
=======
// 07-May-2016 13:45
>>>>>>> i2carduino
//

#ifndef SEDONAC_SEDONA_PLATFORM_H
#define SEDONAC_SEDONA_PLATFORM_H

#define PLATFORM_ID "tridium-generic-unix-1.2.28"

#endif
